### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by CuzyCat** [Ha3MrX/facebook-cracker#35]
$Python facebook.py

File "/data/data/com.termux/files/home/facebook-cracker/facebook.py", line 79
    print wel
    
^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by thewholesihle** [comment]
I its probably because you're running the python2 script using python3, try using `python2 facebook.py`

 I also had the issue and 'converted' the script to python3 by using  `2to3 facebook.py -w`

**Comment by Mocthecat** [comment]
python facebook.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/facebook-cracker/facebook.py", line 5, in <module>
    import mechanize
ModuleNotFoundError: No module named 'mechanize'

**Comment by thewholesihle** [comment]
> python facebook.py Traceback (most recent call last): File "/data/data/com.termux/files/home/facebook-cracker/facebook.py", line 5, in import mechanize ModuleNotFoundError: No module named 'mechanize'

did you try : `pip install mechanize` ?

**Comment by Kate0447** [comment]
Ye

> 

Yes
